#!/bin/bash
# regen-decision-log.sh: rebuild _working-memory/decisionLog.md from ADR
# frontmatter in docs/decisions.md. Idempotent.
#
# Uses Python (installed by default on macOS/Linux) for robust parsing —
# distinguishes horizontal-rule '---' separators from frontmatter delimiters
# by requiring an 'id:' line inside the block.

set -eu
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
ADR_FILE="$REPO_ROOT/docs/decisions.md"
LOG_FILE="$REPO_ROOT/_working-memory/decisionLog.md"

if [ ! -f "$ADR_FILE" ]; then
  echo "decisions.md not found at $ADR_FILE; skipping" >&2
  exit 0
fi

python3 - "$ADR_FILE" > "$LOG_FILE" <<'PYEOF'
import sys, pathlib

text = pathlib.Path(sys.argv[1]).read_text()
lines = text.splitlines()

# State-machine parse. A '---' line is either:
#   - a frontmatter-open (followed eventually by a frontmatter-close)
#   - or a horizontal-rule divider (standalone, not paired)
# We tell them apart by buffering between '---' pairs and only accepting
# blocks that contain an 'id:' line at top level. If a "candidate" block
# turns out to be just an HR (no id:), we DON'T consume the closing '---'
# as the actual frontmatter-open — we look for the next '---' to pair with.

LOOKING, INSIDE = 0, 1
state = LOOKING
buf = []
entries = []

# Strip code-fence content so '---' inside fenced examples doesn't confuse us
in_codefence = False
filtered_lines = []
for line in lines:
    if line.lstrip().startswith('```'):
        in_codefence = not in_codefence
        filtered_lines.append('')  # placeholder to preserve line count
        continue
    filtered_lines.append('' if in_codefence else line)

i = 0
while i < len(filtered_lines):
    line = filtered_lines[i]
    if state == LOOKING:
        if line.strip() == '---':
            state = INSIDE
            buf = []
    else:  # INSIDE
        if line.strip() == '---':
            # Closing candidate — decide whether buf is a real frontmatter
            has_id = any(
                b.split(':', 1)[0].strip() == 'id' and not b.startswith((' ', '-', '#', '\t'))
                for b in buf if ':' in b
            )
            if has_id:
                fields = {}
                for b in buf:
                    if not b or b.startswith((' ', '-', '#', '\t')):
                        continue
                    if ':' not in b:
                        continue
                    k, _, v = b.partition(':')
                    fields[k.strip()] = v.strip()
                if fields.get('id', '').startswith('ADR-'):
                    entries.append(fields)
                state = LOOKING
            else:
                # Not a real frontmatter — this '---' is the next candidate-open
                state = INSIDE
                buf = []
        else:
            buf.append(line)
    i += 1

entries.sort(key=lambda e: (e.get('date', ''), e.get('id', '')), reverse=True)

print("# Decision Log")
print()
print("<!-- Auto-generated by scripts/regen-decision-log.sh from docs/decisions.md frontmatter. -->")
print("<!-- Do not edit by hand — your changes will be overwritten. -->")
print("<!-- Most recent at top. -->")
print()

if not entries:
    print("_No ADRs with frontmatter found in decisions.md._")
else:
    for e in entries:
        date = e.get('date', 'undated')
        adr_id = e.get('id', '?')
        title = e.get('title', '(untitled)')
        status = e.get('status', 'unknown')
        outcome = e.get('decision_outcome', '')
        anchor = adr_id.lower()

        print(f"## {date} — {adr_id}: {title}")
        print()
        print(f"**Status:** {status}")
        if outcome:
            print()
            print(outcome)
        print()
        print(f"→ [docs/decisions.md#{anchor}](../docs/decisions.md#{anchor})")
        print()
PYEOF

echo "✓ Regenerated $LOG_FILE"
